### PR TITLE
Upload code coverage stats to codecov.io

### LINKED ISSUE #25: Set up code coverage stats
We should set up code coverage stats with http://codecov.io/, to make sure we don't drop down on our test coverage.

### PR DESCRIPTION
**Pull request by yuvipanda**
Fix #25

### CODE REVIEW

**Comment by yuvipanda** [comment]
I think this needs owners of the pangeo-gallery organization to approve the codecov.io app. I've sent a request!

**Comment by yuvipanda** [comment]
It says `Error: Missing repository upload token` but succeeds. mfpf.

**Comment by rabernat** [comment]
I'm definitely :+1: on this, but could you try to resolve the conflicts?

**Comment by yuvipanda** [comment]
@rabernat I fixed the conflicts.

**Pull request closed without merging**
